services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src